#!/usr/bin/env python3
"""
tools/file_creator.py

A small CLI to create files safely from templates or direct content. Intended to be called by an AI assistant or by a developer to create many file types on demand.

Usage examples:

# Create a single Python file from a built-in template
python tools/file_creator.py --path tools/port_scanner.py --template port_scanner

# Create multiple files described in a JSON file
python tools/file_creator.py --json requests/create_files.json

# Create a file with literal content
python tools/file_creator.py --path README_NEW.md --content "# New README\nGenerated by AI"

"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Any

# Built-in templates (small starter implementations)
TEMPLATES: Dict[str, str] = {
    "port_scanner": """
#!/usr/bin/env python3
"""Lightweight TCP port scanner"""
import socket
import argparse

def scan(host, ports, timeout=1.0):
    open_ports = []
    for p in ports:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            try:
                s.connect((host, p))
                open_ports.append(p)
            except Exception:
                pass
    return open_ports

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Simple TCP port scanner')
    ap.add_argument('host')
    ap.add_argument('--ports', default='22,80,443', help='Comma separated ports')
    args = ap.parse_args()
    ports = [int(x) for x in args.ports.split(',') if x.strip()]
    print('Scanning', args.host, 'for ports', ports)
    found = scan(args.host, ports)
    if found:
        print('Open ports:', found)
    else:
        print('No open ports found')
""",

    "password_generator": """
#!/usr/bin/env python3
"""Simple password generator utility"""
import secrets
import string
import argparse

ALPHABET = string.ascii_letters + string.digits + string.punctuation

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Generate secure random passwords')
    ap.add_argument('--length', type=int, default=16)
    ap.add_argument('--count', type=int, default=1)
    args = ap.parse_args()
    for _ in range(args.count):
        print(''.join(secrets.choice(ALPHABET) for _ in range(args.length)))
""",

    "network_analyzer": """
#!/usr/bin/env python3
"""Minimal network analyzer that prints interfaces and IPs (Linux)"""
import socket
import subprocess


def get_ip_addresses():
    out = subprocess.check_output(["ip", "-brief", "addr"]).decode('utf-8', errors='ignore')
    print(out)

if __name__ == '__main__':
    print('Interface addresses:')
    try:
        get_ip_addresses()
    except Exception as e:
        print('Failed to enumerate interfaces:', e)
""",

    "vuln_scanner": """
#!/usr/bin/env python3
"""Very small vulnerability scan placeholder - integrate real scanners like nmap/nikto for production"""
print('This is a placeholder for a vulnerability scanner. Integrate nmap, OpenVAS, or other scanners here.')
""",

    "log_analyzer": """
#!/usr/bin/env python3
"""Basic log analyzer: count lines and simple keyword stats"""
import argparse
from collections import Counter

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Analyze a log file for simple stats')
    ap.add_argument('logfile', help='Path to log file')
    ap.add_argument('--top', type=int, default=10, help='Top keywords')
    args = ap.parse_args()
    counter = Counter()
    with open(args.logfile, 'r', errors='ignore') as fh:
        for line in fh:
            for token in line.strip().split():
                counter[token] += 1
    print('Total unique tokens:', len(counter))
    for token, count in counter.most_common(args.top):
        print(token, count)
""",

    "automation_framework": """
#!/usr/bin/env python3
"""Tiny automation entrypoint - a directory of tasks could live alongside this file."""
import argparse
import subprocess

TASKS = {
    'example': ['echo', 'Run an example task']
}

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Run predefined automation tasks')
    ap.add_argument('task')
    args = ap.parse_args()
    cmd = TASKS.get(args.task)
    if not cmd:
        print('Unknown task', args.task)
        raise SystemExit(2)
    subprocess.run(cmd)
""",
}


def sanitize_path(p: str) -> Path:
    """Sanitize and return a safe Path object.

    - Disallow absolute paths
    - Disallow path traversal (..)
    - Resolve relative path to project root (cwd)
    """
    if os.path.isabs(p):
        raise ValueError('Absolute paths are not allowed')
    if '..' in Path(p).parts:
        raise ValueError('Path traversal (..) is not allowed')
    return Path(p)


def ensure_parent(path: Path) -> None:
    parent = path.parent
    if not parent.exists():
        parent.mkdir(parents=True, exist_ok=True)


def create_file(path: Path, content: str, force: bool = False) -> None:
    if path.exists() and not force:
        raise FileExistsError(f'File {path} already exists (use --force to overwrite)')
    ensure_parent(path)
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(content)


def handle_single(args: argparse.Namespace) -> None:
    path = sanitize_path(args.path)
    if args.template:
        template_name = args.template
        if template_name not in TEMPLATES:
            raise KeyError(f'Unknown template: {template_name}')
        content = TEMPLATES[template_name]
    elif args.content:
        content = args.content
    elif args.content_file:
        with open(args.content_file, 'r', encoding='utf-8') as fh:
            content = fh.read()
    else:
        raise ValueError('One of --template, --content, or --content-file must be provided')
    create_file(path, content, force=args.force)
    print(f'Created {path}')


def handle_json(args: argparse.Namespace) -> None:
    with open(args.json, 'r', encoding='utf-8') as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError('JSON file must contain a list of file descriptors')
    created = []
    for item in data:
        # each item: {"path": "foo.py", "template": "port_scanner"} or {"path": "x","content":"..."}
        if 'path' not in item:
            print('Skipping entry without path:', item)
            continue
        path = sanitize_path(item['path'])
        if 'template' in item:
            tpl = item['template']
            if tpl not in TEMPLATES:
                print('Unknown template', tpl, 'skipping')
                continue
            content = TEMPLATES[tpl]
        elif 'content' in item:
            content = item['content']
        elif 'content_file' in item:
            with open(item['content_file'], 'r', encoding='utf-8') as fh:
                content = fh.read()
        else:
            print('No content for', item['path'], 'skipping')
            continue
        try:
            create_file(path, content, force=args.force)
            created.append(str(path))
        except Exception as e:
            print('Failed to create', path, ':', e)
    print('Created files:', created)


def list_templates() -> None:
    print('Available templates:')
    for t in sorted(TEMPLATES.keys()):
        print(' -', t)


def main(argv: Any = None) -> int:
    ap = argparse.ArgumentParser(description='Create files from templates or content (safe).')
    group = ap.add_mutually_exclusive_group(required=False)
    group.add_argument('--path', help='Relative path to create')
    group.add_argument('--json', help='JSON file describing multiple files to create')
    ap.add_argument('--template', help='Use a built-in template name')
    ap.add_argument('--content', help='Literal content for the file')
    ap.add_argument('--content-file', help='Read content from this file')
    ap.add_argument('--force', action='store_true', help='Overwrite existing files')
    ap.add_argument('--list-templates', action='store_true', help='List available templates')
    args = ap.parse_args(argv)

    try:
        if args.list_templates:
            list_templates()
            return 0
        if args.json:
            handle_json(args)
            return 0
        if args.path:
            handle_single(args)
            return 0
        ap.print_help()
        return 1
    except Exception as e:
        print('Error:', e, file=sys.stderr)
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
